### PR TITLE
fix: Add types reference in package.json

### PR DESCRIPTION
**Pull request by MichaelDeBoey**

### CODE REVIEW

**Review by kentcdodds — COMMENTED** [review]
Is this necessary? Don't the typings get picked up automatically when TypeScript finds the `.d.ts`?

**Comment by MichaelDeBoey** [comment]
I've always seen it added to the `package.json`, so I don't think so but I'm not 100% sure

**Comment by kentcdodds** [comment]
I'm pretty sure it's not needed.

**Comment by MichaelDeBoey** [comment]
`type-fest` has it too:
https://github.com/sindresorhus/type-fest/blob/master/package.json#L43

I can look into other packages if you want.

**Comment by kentcdodds** [comment]
Based on [this](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html#including-declarations-in-your-npm-package) it looks like we should, so we will.

**Pull request merged**
