### PR TITLE
chore(validate): Update validate workflow

### PR DESCRIPTION
**Pull request by MichaelDeBoey**

### CODE REVIEW

**Review by kentcdodds — APPROVED** [review]
Perfect. Thanks!

**Comment by kentcdodds** [comment]
Managing all of these is going to be really annoying. Too bad there's not an easier way to share these configurations.

**Comment by MichaelDeBoey** [comment]
Always a pleasure to help out 🙂

**Comment by MichaelDeBoey** [comment]
@kentcdodds Maybe we should take a look into creating our own action, so that one can handle all of it? 🤔

**Pull request merged**
